#!/bin/bash

docker run --rm \
    --net=host \
    -e DISPLAY=$DISPLAY \
    -v $HOME/.Xauthority:/home/developer/.Xauthority \
    -v `pwd`/.netbeans-docker:/home/developer/.netbeans \
    -v `pwd`:/workspace \
    shanemikel/netbeans:v8.0.1
